### ISSUE TITLE
cannot startup the program

### ISSUE THREAD

**Issue by niuaniuaniua** [dotbitHQ/das-contracts#13]

**Comment by linkdesu** [comment]
Hi, sorry for late. We have released the latest version of our project and it's recommand to try the latest version. 

The error you faced is caused by version mismatch between [das-contracts](https://github.com/DeAccountSystems/das-contracts) and [das-types](https://github.com/DeAccountSystems/das-types), and it should be fixed after this release.

**Comment by niuaniuaniua** [comment]
.
